# Generated by Django 4.1.2 on 2022-10-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_rename_company_workout_gym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='Gym',
            new_name='gym',
        ),
    ]
